
// --- ITEM LIMIT --- //

#define ITEM_LIMIT_ADDR_1
#define ITEM_LIMIT_ADDR_2
#define ITEM_LIMIT_ADDR_3
#define ITEM_LIMIT_ADDR_4
#define ITEM_LIMIT_ADDR_5
#define ITEM_LIMIT_ADDR_6
#define ITEM_LIMIT_ADDR_7
#define ITEM_LIMIT_ADDR_8
#define ITEM_LIMIT_ADDR_9
#define ITEM_LIMIT_ADDR_10
#define ITEM_LIMIT_ADDR_11
#define ITEM_LIMIT_ADDR_12
#define ITEM_LIMIT_ADDR_13
#define ITEM_LIMIT_ADDR_14
#define ITEM_LIMIT_ADDR_15
#define ITEM_LIMIT_ADDR_16
#define ITEM_LIMIT_ADDR_17
#define ITEM_LIMIT_ADDR_18
#define ITEM_LIMIT_ADDR_19
#define ITEM_LIMIT_ADDR_20
#define ITEM_LIMIT_ADDR_21
#define ITEM_LIMIT_ADDR_22
#define ITEM_LIMIT_ADDR_23

// --- Character Item Index Limit --- //
// --- Array Size = Size * 1404 = Value --- //

#define OFF_CSHELL_CHARACTER_ITEM_INDEX_LIMIT_1 0x55C605+0x1
#define OFF_CSHELL_CHARACTER_ITEM_INDEX_LIMIT_2 0x55B849+0x1
#define OFF_CSHELL_CHARACTER_ITEM_INDEX_LIMIT_3 0x55C0DB+0x5
#define OFF_CSHELL_CHARACTER_ITEM_INDEX_ARRAY_1 0x5A19BD+0x1

// --- Weapon Bute Limit --- //
// --- Struct Size = Bute * 18332 = Value --- //

#define OFF_CSHELL_WEAPON_BUTE_STRUCT_SIZE_1 0x563642
#define OFF_CSHELL_WEAPON_LIMIT_1 0x5756C2+0x2
#define OFF_CSHELL_WEAPON_LIMIT_2 0x5636AF+0x2
#define OFF_CSHELL_WEAPON_LIMIT_3 0x21215+0x2
#define OFF_CSHELL_WEAPON_LIMIT_4 0x1A7E08+0x5
#define OFF_CSHELL_WEAPON_LIMIT_5 0xDB0F5D+0x2
#define OFF_CSHELL_WEAPON_LIMIT_6 0xDB0F35+0x1
#define OFF_CSHELL_WEAPON_LIMIT_7 0xDB0F63+0x3
#define OFF_WEAPON_LIMIT_1 0x1C969A //
#define OFF_WEAPON_LIMIT_2 0x1C96A8 //
#define OFF_WEAPON_LIMIT_3 0x1C96B8 //
#define OFF_WEAPON_LIMIT_4 0x1C96D7 //
#define OFF_WEAPON_LIMIT_5 0x1C96E7 //
#define OFF_WEAPON_LIMIT_6 0x1C96FA //

// --- Sound Limit --- //

#define OFF_CSHELL_SOUND_LIMIT_1 0x55D652+0x2

// --- ANTICHEAT NEEDED --- //

#define AC_PLAYER_USN 0x1739048
#define AC_PLAYER_URN 0x1739050
#define AC_PLAYER_IGN 0x171DCA8
#define AC_PLAYER_PWD 0x1739065
#define AC_SERVER_SIP 0x1738F48
#define AC_SERVER_SPORT 0x1738FC8
#define ADDR_GAMESRV_PORT_POINTER 0x0171D820
#define ADDR_GARNET_SYSTEM_POINTER 0x01AB8D50
#define ADDR_LOBBY_POINTER 0x171BC00


// --- IP & PORT --- //

//const char* BAN_IP = _xor("127.0.0.1").c_str();
//unsigned short BAN_PORT = 8080;

// --- STRING & BYTES --- //

#define OFF_CSHELL_CLIENT_BANNER 0xF38650
#define OFF_CSHELL_SCREENSHOT 0xFF5B74
#define OFF_CSHELL_WEBVIEW_POINTER 0x018ABAEC
#define OFF_CSHELL_SCREENSHOT_ 0x31F66F
#define OFF_CSHELL_INAGMEADDR 0x016B3F58 + 0x7C
#define OFF_CSHELL_ROOMADDRESS 0x1668228

#define OFF_CSHELL_M200ADDRESS 0x16F3A5B // 0x16F3A5F
#define OFF_CSHELL_M200ADDRES2S 0x00162498

#define OFF_CLIENT_HGW_STRING 0xDAE713
//#define OFF_CSHELL_WEAPONMGRADDR 

#define OFF_CSHELL_MAXMEMORY_JUMP 0x515E96
#define OFF_CSHELL_MAXFRAME_JUMP 0x515E1B
#define OFF_CSHELL_POS_JUMP 0xB4ADB+0x1D9 //
#define OFF_CSHELL_POS_2_JUMP 0x515FB6
#define OFF_CSHELL_POS_3_JUMP 0xB4ADB+0x1F1 //
#define OFF_CSHELL_DEBUG_RANKED_BYPASS_JUMP 0x44B27A

// --- S2S --- //

#define ADDR_SENDTOSERVER 0x297F80
#define ADDR_LTCLIENT 0x32FC48

// --- MESSAGE BOX --- //

#define INGAME_MSG 0x19C800
//#define INGAME_MSG_PUSH_1 0x0
//#define INGAME_MSG_PUSH_2 0x76
//#define INGAME_MSG_PUSH_3 0x2F

#define INGAME_MSG_PUSH_1 0x0
#define INGAME_MSG_PUSH_2_CRASH 0x76
#define INGAME_MSG_PUSH_2 0x77
#define INGAME_MSG_PUSH_3 0x2F

#define INGAME_MSG_PUSH_DONATE 0x36
#define INGAME_MSG_PUSH_CLAN 0xA7
#define INGAME_MSG_ADDRESS 0x14


// --- HWID CHANGE --- //

#define OFF_CSHELL_CLIENT_MAC 0x1739200
#define OFF_CSHELL_CLIENT_AUTH_DATA 0x1739210
#define OFF_CLIENT_MAC 0xD9E625
#define OFF_CLIENT_CPU 0xD9E580
#define OFF_CLIENT_CMD 0xDAE713

// --- GAME CHAT --- //

#define OFF_CSHELL_MY_CHAT_F 0x1E802E0
#define OFF_CSHELL_MY_CHAT_L 0x1E802E3
#define OFF_CSHELL_OTHER_CHAT 0x1E77A1D
#define INGAME_CHAT_ECX 0x1743220
#define INGAME_CHAT_CALL 0x195D80
#define INGAME_CHAT_PACKET 0x78F2C0

// --- DISCORD RPC --- //

#define ADDR_DISCORD_ID 0x11EDD0

// --- M200 FUNCTION --- //

#define ADDR_CSHELL_CROSSHAIR_OPEN 0x1E73B3D
#define ADDR_CSHELL_VISIBLE_CHECK 0x163C800

// --- VOICE CHAT --- //

#define ADDR_CSHELL_ROOM_PORT 0x171D84C


#define WEAPON_FOV_OFF  0x0A34 // 
#define WEAPON_RELOAD_ANIM_RATIO  0x112C //
#define WEAPON_CHANGE_ANIM_RATIO  0x1130 //
#define WEAPON_RANGE 0xBCC //

#define WEAPON_KNOCKBACK_1  0x30E0 //
#define WEAPON_KNOCKBACK_2  (WEAPON_KNOCKBACK_1 + 0x4) //

#define WEAPON_BULLET_POS_OFF_1  0x29EC //
#define WEAPON_BULLET_POS_OFF_2  (WEAPON_BULLET_POS_OFF_1 + 0x4) //
#define WEAPON_BULLET_POS_OFF_3  (WEAPON_BULLET_POS_OFF_2 + 0x4) //

#define WEAPON_SHOT_REACT_PITCH_1  0x2BCC // int32
#define WEAPON_SHOT_REACT_PITCH_2  (WEAPON_SHOT_REACT_PITCH_1 + 0x4) //
#define WEAPON_SHOT_REACT_PITCH_3  (WEAPON_SHOT_REACT_PITCH_2 + 0x4) //

#define WEAPON_SHOT_REACT_YAW_1  0x29F8 // int32
#define WEAPON_SHOT_REACT_YAW_2  (WEAPON_SHOT_REACT_YAW_1 + 0x4) //
#define WEAPON_SHOT_REACT_YAW_3  (WEAPON_SHOT_REACT_YAW_2 + 0x4) //

#define WEAPON_DETAIL_PERTURB_SHOT_1  0x11AC //
#define WEAPON_DETAIL_PERTURB_SHOT_2  (WEAPON_DETAIL_PERTURB_SHOT_1 + 0x4)
#define WEAPON_DETAIL_PERTURB_SHOT_3  (WEAPON_DETAIL_PERTURB_SHOT_2 + 0x4)
#define WEAPON_DETAIL_PERTURB_SHOT_4  (WEAPON_DETAIL_PERTURB_SHOT_3 + 0x4)
#define WEAPON_DETAIL_PERTURB_SHOT_5  (WEAPON_DETAIL_PERTURB_SHOT_4 + 0x4)

#define WEAPON_DETAIL_REACT_PITH_SHOT_1  0x11E8 //
#define WEAPON_DETAIL_REACT_PITH_SHOT_2  (WEAPON_DETAIL_REACT_PITH_SHOT_1 + 0x4)
#define WEAPON_DETAIL_REACT_PITH_SHOT_3  (WEAPON_DETAIL_REACT_PITH_SHOT_2 + 0x4)
#define WEAPON_DETAIL_REACT_PITH_SHOT_4  (WEAPON_DETAIL_REACT_PITH_SHOT_3 + 0x4)
#define WEAPON_DETAIL_REACT_PITH_SHOT_5  (WEAPON_DETAIL_REACT_PITH_SHOT_4 + 0x4)

#define WEAPON_DETAIL_REACT_YAW_SHOT_1  0x1224 //
#define WEAPON_DETAIL_REACT_YAW_SHOT_2  (WEAPON_DETAIL_REACT_YAW_SHOT_1 + 0x4)
#define WEAPON_DETAIL_REACT_YAW_SHOT_3  (WEAPON_DETAIL_REACT_YAW_SHOT_2 + 0x4)
#define WEAPON_DETAIL_REACT_YAW_SHOT_4  (WEAPON_DETAIL_REACT_YAW_SHOT_3 + 0x4)
#define WEAPON_DETAIL_REACT_YAW_SHOT_5  (WEAPON_DETAIL_REACT_YAW_SHOT_4 + 0x4)

#define WEAPON_CHAIR_PER_REAL_SIZE  0x2F74 //
#define WEAPON_SUBTYPE  0xBE8 //

#define WEAPON_PERTURB_MIN_1  0x0B54 // 
#define WEAPON_PERTURB_MIN_2  (WEAPON_PERTURB_MIN_1 + 0x4)
#define WEAPON_PERTURB_MIN_3  (WEAPON_PERTURB_MIN_2 + 0x4)
#define WEAPON_PERTURB_MIN_4  (WEAPON_PERTURB_MIN_3 + 0x4)
#define WEAPON_PERTURB_MIN_5  (WEAPON_PERTURB_MIN_4 + 0x4)


#define WEAPON_PERTURB_MAX_1  0x0B90 //
#define WEAPON_PERTURB_MAX_2  (WEAPON_PERTURB_MAX_1 + 0x4)
#define WEAPON_PERTURB_MAX_3  (WEAPON_PERTURB_MAX_2 + 0x4)
#define WEAPON_PERTURB_MAX_4  (WEAPON_PERTURB_MAX_3 + 0x4)
#define WEAPON_PERTURB_MAX_5  (WEAPON_PERTURB_MAX_4 + 0x4)

#define WEAPON_REPEAT_FIRE  0x1260 // 

#define MAX_PLAYERS_IN_ROOM		32
#define INVALID_AIM_TARGET		-1

#define FLAG_VISIBLE_CF			1
#define FLAG_RAYHIT_CF			1 << 13

#define Player_Size 0xD80
#define Player_Offset (0x20C) // 0x20B , 0x208 , 0x214 , 0x208 + 0x3
#define GLPI 0x7B1C0